name: portfolio
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-55.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  google_fonts: ^2.3.2
  native_scroll: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/comfortaa/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/comfortaa/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/comfortaa/Comfortaa-Bold.ttf
          weight: 700
    - family: Garamond
      fonts:
        - asset: assets/fonts/garamond/EBGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/garamond/EBGaramond-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/garamond/EBGaramond-Medium.ttf
          weight: 500
        - asset: assets/fonts/garamond/EBGaramond-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/garamond/EBGaramond-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/garamond/EBGaramond-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/garamond/EBGaramond-Bold.ttf
          weight: 700
        - asset: assets/fonts/garamond/EBGaramond-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/garamond/EBGaramond-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/garamond/EBGaramond-ExtraBoldItalic.ttf
          weight: 800
          style: italic
